### ISSUE TITLE
Error ([AutoDeploy] Autodeploy failed : /opt/domains/sormas/autodeploy/sormas-ui.war.]])

### ISSUE THREAD

**Issue by nnumitor** [hzi-braunschweig/SORMAS-Docker#85]
Hello, 

I have some errors after install see there :

# docker-compose up -d
sormas-docker_postgres_1 is up-to-date
sormas-docker_autoheal_1 is up-to-date
sormas-docker_pg_dump_1 is up-to-date
Creating sormas-docker_sormas_1 ... done

ERROR: for apache2  Container "0968a17e6de0" is unhealthy.
ERROR: Encountered errors while bringing up the project.

And logs 
docker logs -f sormas-docker_sormas_1 :

[2020-08-04T08:40:40.513+0200] [Payara 5.2020] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=96 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1596523240513] [levelValue: 1000] [[
  Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:542)
	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:81)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:687)
	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:421)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:159)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:171)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:283)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:362)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:621)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
	at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:149)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:532)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:437)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:371)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:362)
	at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Lookup failed for 'java:global/sormas-ear/sormas-backend/ConfigFacade' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming}
	at de.symeda.sormas.api.FacadeProvider.lookupEjbRemote(FacadeProvider.java:282)
	at de.symeda.sormas.api.FacadeProvider.getConfigFacade(FacadeProvider.java:186)
	at de.symeda.sormas.ui.StartupShutdownService.startup(StartupShutdownService.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.BeanCallbackInterceptor.intercept(InterceptorManager.java:1022)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:204)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
	at jdk.internal.reflect.GeneratedMethodAccessor262.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:978)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:204)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at jdk.internal.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:978)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:418)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:381)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:2048)
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:529)
	... 37 more
Caused by: javax.naming.NamingException: Lookup failed for 'java:global/sormas-ear/sormas-backend/ConfigFacade' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NameNotFoundException: ConfigFacade not found]
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:496)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
	at de.symeda.sormas.api.FacadeProvider.lookupEjbRemote(FacadeProvider.java:280)
	... 65 more
Caused by: javax.naming.NameNotFoundException: ConfigFacade not found
	at com.sun.enterprise.naming.impl.TransientContext.doLookup(TransientContext.java:237)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:204)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
	at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
	at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:70)
	at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.lookup(LocalSerialContextProviderImpl.java:114)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:483)
	... 69 more
]]

[2020-08-04T08:40:40.550+0200] [Payara 5.2020] [WARNING] [NCLS-DEPLOYMENT-02036] [javax.enterprise.system.tools.deployment.autodeploy] [tid: _ThreadID=96 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1596523240550] [levelValue: 900] [[
  Error occurred during deployment: Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService. Please see server.log for more details.]]

[2020-08-04T08:40:40.550+0200] [Payara 5.2020] [WARNING] [NCLS-DEPLOYMENT-02036] [javax.enterprise.system.tools.deployment.autodeploy] [tid: _ThreadID=96 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1596523240550] [levelValue: 900] [[
  [AutoDeploy] Autodeploy failed : /opt/domains/sormas/autodeploy/sormas-ui.war.]]

Can you help me please ?
Thanks

**Comment by asohh** [comment]
hey,

there should be some more stacktraces in the log.

For examlpe this this is part of one if the app url is wrong:
[WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=100 _ThreadName=payara-executor-service-scheduled-task] [timeMillis: 1596637920163] [levelValue: 900] [[
  
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.IllegalArgumentException: Property 'app.url' does not point to a compatible app version: 'https://xxx.xxxx.xxxx/downloads/release/sormas-1.45.0-release.apk'. Minimum is '1.46.0'

Could you look for some stacktrace like this and send it to me.

**Comment by nliakm** [comment]
Closed due to inactivity.
